name: Deploy Sanity Studio
on: 
  push:
    branches: ['main']
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/cms
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
            node-version: 19.x

      - name: Install dependencies
        run: |
            npm install

      - name: Deploy Sanity Studio
        run: SANITY_AUTH_TOKEN="$SANITY_AUTH_TOKEN" npx sanity deploy
        env: 
            SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}